___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!


#### 1. Import NumPy Library

In [1]:
import numpy as np

#### 2. Create an array from my_list=[5,10,15,20,25]

In [ ]:
my_list = np.array([5,10,15,20,25])
my_list

array([ 5, 10, 15, 20, 25])

#### 3. Generate an array 5x5 zeros 

In [ ]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### 4. Generate an array 4x4 ones assign data type int

In [ ]:
np.ones([4,4],dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

#### 5. Make all the values of the array above 7

In [ ]:
np.array([[7,7,7,7],[7,7,7,7],[7,7,7,7],[7,7,7,7]])

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 6. Create same array above with full method

In [ ]:
np.full([4,4],7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 7. Create an array of even integers from 2 to 16 

In [ ]:
np.arange(2,17,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16])

#### 8. Create a 5x5 matrix with values between 0 to 25

In [ ]:
np.arange(25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 9. Create a 5x5 matrix with values between 0 to 25 using linspace

In [ ]:
np.linspace(0,25,25)

array([ 0.        ,  1.04166667,  2.08333333,  3.125     ,  4.16666667,
        5.20833333,  6.25      ,  7.29166667,  8.33333333,  9.375     ,
       10.41666667, 11.45833333, 12.5       , 13.54166667, 14.58333333,
       15.625     , 16.66666667, 17.70833333, 18.75      , 19.79166667,
       20.83333333, 21.875     , 22.91666667, 23.95833333, 25.        ])

#### 10. Create 5 random number with numpy

In [ ]:
np.random.rand(5)

array([0.0431703 , 0.39065299, 0.87960073, 0.73642323, 0.53839301])

#### 11. Create random normal distributed 5x5 array

In [ ]:
np.random.randn(5,5)

array([[-1.88145979, -0.33694765,  1.00329733, -0.78862807, -0.95450456],
       [ 1.3872682 , -1.05838181,  1.38137969, -0.58068211, -1.45203318],
       [-0.1202232 , -0.02930381,  0.46451676, -0.62666937, -0.14675805],
       [-0.30564453,  1.83376643,  0.82751037, -0.63556272,  1.44643513],
       [ 0.63463514, -0.67219484, -0.17806175,  0.81716206, -1.14449609]])

#### 12. Create 3x4 shaped array with random int numbers between 20 and 50 with numpy

In [ ]:
np.random.randint(20,50,[3,4])

array([[41, 44, 49, 32],
       [43, 20, 20, 49],
       [26, 39, 39, 44]])

#### 13. Reshape the array below with shape 6x8

In [ ]:
ranarr = np.random.randint(0,60,48)

In [ ]:
ranarr

array([38,  7,  9, 37, 58, 44, 24, 42,  7, 30, 56, 39, 15, 59, 39, 35, 58,
       40, 49,  9, 11,  1, 27, 57,  6, 14,  3, 10,  4,  1, 45, 35, 24,  4,
        5, 37, 24, 53,  2,  0, 18, 40, 56, 14, 53, 21, 33,  6])

In [ ]:
ranarr = ranarr.reshape(6,8)
ranarr

array([[38,  7,  9, 37, 58, 44, 24, 42],
       [ 7, 30, 56, 39, 15, 59, 39, 35],
       [58, 40, 49,  9, 11,  1, 27, 57],
       [ 6, 14,  3, 10,  4,  1, 45, 35],
       [24,  4,  5, 37, 24, 53,  2,  0],
       [18, 40, 56, 14, 53, 21, 33,  6]])

In [ ]:
#reshape with -1
ranarr = ranarr.reshape(-1,12)
ranarr

array([[38,  7,  9, 37, 58, 44, 24, 42,  7, 30, 56, 39],
       [15, 59, 39, 35, 58, 40, 49,  9, 11,  1, 27, 57],
       [ 6, 14,  3, 10,  4,  1, 45, 35, 24,  4,  5, 37],
       [24, 53,  2,  0, 18, 40, 56, 14, 53, 21, 33,  6]])

## Numpy Indexing and Selection


In [ ]:
#Create array below
mat=np.arange(1,17).reshape(4,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

#### 14. Write code that reproduces the output shown below.<br>

In [ ]:
mat[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

#### 15. Get the first column of the array.

In [ ]:
mat[:,0]

array([ 1,  5,  9, 13])

#### 16. Get the values in 2nd row for every 2 step.

In [ ]:
mat[1,::2]

array([5, 7])

#### 17.Assign 77 to every cell in 3rd column.

In [ ]:
mat[:,2]=77
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

#### 18. Take 2nd row 1st column, 4th row 2nd column.

In [ ]:
mat[[1,3],[0,1]]

array([ 5, 14])

#### 19. Take between 2nd and last row with step 2 and between 1 and last column with step 2.

In [ ]:
mat[1::2,0::2]

array([[ 5, 77],
       [13, 77]])

## NumPy Operations

#### 20. Get the sum of values smaller than 10 and values bigger than 12 from array above 

In [ ]:
mat[mat < 10]

array([1, 2, 4, 5, 6, 8, 9])

In [ ]:
mat[mat > 12]

array([77, 77, 77, 13, 14, 77, 16])

In [ ]:
mat[mat < 10] + mat[mat > 12]

array([78, 79, 81, 18, 20, 85, 25])

#### 21. Get the standard deviation of the result above

In [ ]:
x = mat[mat < 10] + mat[mat > 12]

In [ ]:
np.std(x)

29.700546274093877

#### 22. Get the sum of second column from array above

In [ ]:
#print array here
mat=np.arange(1,17).reshape(4,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
mat[:,1].sum()

32

#### 23. Get the median,mean and std of 3rd row from array above

In [ ]:
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [ ]:
mat[2]

array([ 9, 10, 77, 12])

In [ ]:
#median
np.median(mat[2])

10.5

In [ ]:
#mean
np.mean(mat[2])

10.5

In [ ]:
#std
np.std(mat[2])

1.118033988749895

# Pandas Section

In [1]:
import pandas as pd

In [5]:
cd sample_data/

/content/sample_data


**Read Salaries.csv take a look at first 5 rows, df info and df statistical measurements**

In [6]:
sal=pd.read_csv('Salaries.csv')
sal.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

In [ ]:
sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


C:\Users\win7\JUPYTER


In [ ]:
sal.describe()

Id        BasePay  ...  Notes  Status
count  148654.000000  148045.000000  ...    0.0     0.0
mean    74327.500000   66325.448841  ...    NaN     NaN
std     42912.857795   42764.635495  ...    NaN     NaN
min         1.000000    -166.010000  ...    NaN     NaN
25%     37164.250000   33588.200000  ...    NaN     NaN
50%     74327.500000   65007.450000  ...    NaN     NaN
75%    111490.750000   94691.050000  ...    NaN     NaN
max    148654.000000  319275.010000  ...    NaN     NaN

[8 rows x 10 columns]

**How many different year value are there**

In [ ]:
# sal.groupby(["Year"])["Year"].count()
sal.value_counts("Year")

Year
2014    38123
2013    37606
2012    36766
2011    36159
dtype: int64

**Print out max and avg Totalpay**

In [ ]:
#max
np.max(sal["TotalPay"])

567595.43

In [ ]:
#avg
np.mean(sal["TotalPay"])

74768.321971703

**How many records are there which have TotalPay bigger than avg TotalPay**

In [ ]:
sal[sal["TotalPay"] > np.mean(sal["TotalPay"])]["TotalPay"].count()

69489

**How much does ALBERT PARDINI make (including benefits)?**

In [ ]:
sal[sal["EmployeeName"]=="ALBERT PARDINI"]["TotalPayBenefits"]

2    335279.91
Name: TotalPayBenefits, dtype: float64

**Who is lowest paid person**

In [ ]:
sal[sal["TotalPayBenefits"]==np.min(sal["TotalPayBenefits"])]["EmployeeName"]

148653    Joe Lopez
Name: EmployeeName, dtype: object

**What are the unique Jobs in dataset?**

*   Liste öğesi
*   Liste öğesi



In [ ]:
sal["JobTitle"].unique()

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)

**List 3 least common Jobs**

In [ ]:
sal.JobTitle.value_counts().sort_values()[:3]

MAYORAL STAFF V                            1
SECRETARY,JUVENILE PROBATION COMMISSION    1
COURT AD RESOLUTION COORDINATOR            1
Name: JobTitle, dtype: int64

**How many people earned more than avg in 2012**

In [ ]:
# sal[sal["TotalPayBenefits"] > np.mean(sal["TotalPayBenefits"])][sal["Year"]==2012]["TotalPayBenefits"].count()
sal[ (sal.TotalPayBenefits>sal.TotalPayBenefits.mean()) & (sal.Year==2012) ]["TotalPayBenefits"].count()

20366

**How many people have the word Manager in their job title?**

In [ ]:
#use apply function here


**Take Id,EmployeeName,JobTitle,TotalPay and TotalPayBenefits columns with iloc and assign it as sal_new dataframe**

In [ ]:
sal.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

In [18]:
sal_new= sal.iloc[:,[0,1,2,7,8]]
sal_new

Id       EmployeeName  ...   TotalPay  TotalPayBenefits
0          1     NATHANIEL FORD  ...  567595.43         567595.43
1          2       GARY JIMENEZ  ...  538909.28         538909.28
2          3     ALBERT PARDINI  ...  335279.91         335279.91
3          4  CHRISTOPHER CHONG  ...  332343.61         332343.61
4          5    PATRICK GARDNER  ...  326373.19         326373.19
...      ...                ...  ...        ...               ...
59228  59229       Gwen Brister  ...   57439.54          84694.76
59229  59230    Shawn Sherburne  ...   58734.01          84689.54
59230  59231         George Toy  ...   56980.73          84685.62
59231  59232         Henry Wong  ...   56525.00          84685.25
59232  59233               Dian  ...        NaN               NaN

[59233 rows x 5 columns]

**Take columns betweeen EmployeeName and TotalPayBenefits with loc and assign it o sal_new df**
 

In [22]:
sal_new= sal.loc[:,["EmployeeName","JobTitle","TotalPay","TotalPayBenefits"]]
sal_new

EmployeeName  ... TotalPayBenefits
0         NATHANIEL FORD  ...        567595.43
1           GARY JIMENEZ  ...        538909.28
2         ALBERT PARDINI  ...        335279.91
3      CHRISTOPHER CHONG  ...        332343.61
4        PATRICK GARDNER  ...        326373.19
...                  ...  ...              ...
59228       Gwen Brister  ...         84694.76
59229    Shawn Sherburne  ...         84689.54
59230         George Toy  ...         84685.62
59231         Henry Wong  ...         84685.25
59232               Dian  ...              NaN

[59233 rows x 4 columns]

**Print out the names of the employees who earn more than min, but less than avg**

In [7]:
new_sal = pd.DataFrame(sal)
new_sal.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

In [11]:
new_sal[(new_sal.TotalPayBenefits < new_sal.TotalPayBenefits.mean()) & (new_sal.TotalPayBenefits > new_sal.TotalPayBenefits.min())][["EmployeeName"]]

EmployeeName
10806          KWE LEE
10807   MIGUEL CARO JR
10808    JOANNE MORRIS
10809    LAYLA WELBORN
10810          LE BANH
...                ...
148648     Leon Walker
148649   Roy I Tillery
148650    Not provided
148651    Not provided
148652    Not provided

[75649 rows x 1 columns]